application: curiousdognightapp
version: 2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/icons/favicon.ico
  upload: application/static/icons/favicon.ico

- url: /apple-touch-icon.png
  static_files: application/static/icons/apple-touch-icon.png
  upload: application/static/icons/apple-touch-icon.png

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /static
  static_dir: application/static

- url: .*
  script: application.app